
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/xuzhengkai/Desktop/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.3.0 - x86_64
